const adminBlackKeywords = [
  'c++',
  'flutter',
  'vue',
  'angular',
  'python',
  'питон',
  'пайтон',
  'django',
  'джанго',
  'flask',
  'fastapi',
  'обзвон',
  'zenoposter',
  'zenodroid',
  'zenno',
  'зенно',
  'trading',
  'metatrader',
  'bitcoin',
  'биткоин',
  'binance',
  'криптовалют',
  'trc20',
  'вирус',
  'dle',
  'joomla',
  'magento',
  'elementor',
  'элементор',
  'webasyst',
  'woocommerce',
  'wordpress',
  'вордпрес',
  'laravel',
  '1c',
  '1с',
  'php',
  'yii2',
  'bitrix',
  'битрикс',
  'б24',
  'modx',
  'tilda',
  'тильд',
  'unity',
  'юнити',
  'unreal',
  'ue4',
  'ue5',
  'opencart',
  'tik-tok',
  'тик-ток',
  'тикток',
  'asp.net',
  'android',
  'андроид',
  'kotlin',
  'ucoz',
  'admob',
  'pikabu',
  'пикабу',
  'powershell',
  'ozon',
  'arduino',
  'google',
  'яндекс',
  'telegram',
  'телеграм',
  'комментатор',
  'бот',
  'парсер',
  'парсинг',
  'постинг',
  'нейросеть',
  'платеж',
  'wildberries',
  'вконтакте',
  'oracle',
  'копия',
  'скопиров',
  'selenium',
  'recaptcha',
  'excel',
  'эксель',
  'shopify',
  'linux',
  'webgl',
  'игре',
  'игру',
  'amocrm',
  'бирж',
  'minecraft',
  'майнкрафт',
  'twitch',
  'юкасса',
  'crypto',
  'scraper',
  'golang',
  'c-sharp',
  'ruby-on-rails',
  'aws',
  'safari',
  'авито',
  'производительность',
];

export const defaultUsers = [
  {
    uuid: '7742d292-9d2c-4caa-99c0-74e536f373b1',
    email: 'grogu@gmail.com',
    password: '$2b$08$ziTBl.Y9ir6ZX22jil3kSuknYgtumgbHbo9Vm/pPJ51VFjDRAuOXS',
    is_admin: true,
    subscriptions: '{}',
    keywords_black: '{}',
  },
  {
    uuid: '75fdeead-bc7f-455f-82df-da45d39dcd7a',
    email: 'admin@gmail.com',
    password: '$2b$08$ziTBl.Y9ir6ZX22jil3kSuknYgtumgbHbo9Vm/pPJ51VFjDRAuOXS',
    is_admin: true,
    subscriptions: '{16cf9dcf-08a9-47c0-a372-8a06b78ef167,55a2c33e-dd00-463f-aaaf-911036993274,749ce078-70c2-46e1-b5e6-98b1dad9a326,ea12cd10-be78-49f6-b10a-0e1640b8e40f,f26ff7d3-eba0-447e-a611-33efb1faea85,9d0aee7c-9bb9-450c-b073-28c91289ec8a}',
    keywords_black: `{${adminBlackKeywords.join(',')}}`,
  }
];

